baseURL = "/"
title = "infilos.com"
languageCode = "en-us"
theme = ["docsy"]

# Will give values to .Lastmod etc.
#enableGitInfo = true
enableRobotsTXT = true

# Language settings
contentDir = "content"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true
enableMissingTranslationPlaceholders = true
disableKinds = ["taxonomy", "taxonomyTerm"]
staticDir = ["static"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false

# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false

#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 95
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "UA-123062585-1"

[languages.zh]
title = "infilos.com"
description = "Infilos Wiki Website"
languageName = "中文"
contentDir = "content"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
# See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
style = "tango"
# Uncomment if you want your chosen highlight style used for code blocks without a specified language
guessSyntax = "true"

# Everything below this are Site Params

# Comment out if you don't want the "print entire section" link enabled.
[outputs]
section = ["HTML", "print"]

[params]
copyright = "infilos.com"
#privacy_policy = "https://policies.google.com/privacy"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Flag used in the "version-banner" partial to decide whether to display a 
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the 
# current doc set.
version = "0.0"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://infilos.com"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/infilos/infilos.com"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
#github_project_repo = "https://github.com/google/docsy"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Uncomment this if you have a newer GitHub repo with "main" as the default branch,
# or specify a new value if you want to reference another branch in your GitHub links
# github_branch= "main"

# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "332a2cfd98d9f50d7"

# Enable Algolia DocSearch
algolia_docsearch = false
# Enable Lunr.js offline search
offlineSearch = false

# Enable syntax highlighting and copy buttons on code blocks with Prism
#prism_syntax_highlighting = false

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = true

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/infilos/infilos.com/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/infilos/infilos.com/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page, 
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = false

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.

# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
name = "Weibo"
url = "https://weibo.com/u/3848950217"
icon = "fab fa-weibo"
desc = "Follow us on Weibo to get the latest news!"
[[params.links.developer]]
name = "Twitter"
url = "https://twitter.com/zhange_zzg"
icon = "fab fa-twitter"
desc = "Follow us on Twitter to get the latest news!"
[[params.links.developer]]
name = "Stack Overflow"
url = "https://stackoverflow.com"
icon = "fab fa-stack-overflow"
desc = "Practical questions and curated answers"
[[params.links.developer]]
name = "GitHub"
url = "https://github.com/infilos/infilos.com"
icon = "fab fa-github"
desc = "Development takes place here!"

# top menu
[menu]

##
[[languages.zh.menu.main]]
identifier = "基础"
name = "基础"
weight = 1

[[languages.zh.menu.main]]
parent = "基础"
name = "操作系统"
url = "基础知识/操作系统"
weight = 1

[[languages.zh.menu.main]]
parent = "基础"
name = "性能之殇"
url = "基础知识/性能之殇"
weight = 2

[[languages.zh.menu.main]]
parent = "基础"
name = "IO 模型"
url = "基础知识/io模型"
weight = 3

[[languages.zh.menu.main]]
parent = "基础"
name = "网络基础"
url = "基础知识/网络基础"
weight = 4

[[languages.zh.menu.main]]
parent = "基础"
name = "TCP-IP"
url = "基础知识/tcp-ip"
weight = 5

[[languages.zh.menu.main]]
parent = "基础"
name = "HTTP"
url = "基础知识/http"
weight = 6

##
[[languages.zh.menu.main]]
identifier = "语言"
name = "语言"
weight = 2

[[languages.zh.menu.main]]
parent = "语言"
name = "Java 编程"
url = "编程语言/java"
weight = 1

[[languages.zh.menu.main]]
parent = "语言"
name = "JVM 核心"
url = "编程语言/jvm-core"
weight = 2

[[languages.zh.menu.main]]
parent = "语言"
name = "JVM 并发"
url = "编程语言/jvm-concurrent"
weight = 3

[[languages.zh.menu.main]]
parent = "语言"
name = "Scala 编程"
url = "编程语言/scala"
weight = 4

##
[[languages.zh.menu.main]]
identifier = "框架库"
name = "框架库"
weight = 3

[[languages.zh.menu.main]]
parent = "框架库"
name = "Spring"
url = "框架与库/spring"
weight = 1

[[languages.zh.menu.main]]
parent = "框架库"
name = "Hikari"
url = "框架与库/hikari"
weight = 2

[[languages.zh.menu.main]]
parent = "框架库"
name = "Parboiled"
url = "框架与库/parboiled"
weight = 3

##
[[languages.zh.menu.main]]
identifier = "分布式"
name = "分布式"
weight = 4

[[languages.zh.menu.main]]
parent = "分布式"
name = "基本构成"
url = "分布式/base"
weight = 1

##
[[languages.zh.menu.main]]
identifier = "大数据"
name = "大数据"
weight = 5

[[languages.zh.menu.main]]
parent = "大数据"
name = "存储系统"
url = "存储系统"
weight = 1

[[languages.zh.menu.main]]
parent = "大数据"
name = "查询系统"
url = "查询系统"
weight = 2

[[languages.zh.menu.main]]
parent = "大数据"
name = "消息系统"
url = "消息系统"
weight = 3

[[languages.zh.menu.main]]
parent = "大数据"
name = "处理系统"
url = "处理系统"
weight = 4

[[languages.zh.menu.main]]
parent = "大数据"
name = "管理系统"
url = "管理系统"
weight = 5

##
[[languages.zh.menu.main]]
identifier = "中后台"
name = "中后台"
weight = 6

[[languages.zh.menu.main]]
parent = "中后台"
name = "基础设施"
url = "基础设施"
weight = 1

[[languages.zh.menu.main]]
parent = "中后台"
name = "交互界面"
url = "交互界面"
weight = 2

[[languages.zh.menu.main]]
parent = "中后台"
name = "业务系统"
url = "业务系统"
weight = 3

##
[[languages.zh.menu.main]]
identifier = "模式架构"
name = "模式架构"
weight = 7

[[languages.zh.menu.main]]
parent = "模式架构"
name = "设计模式"
url = "模式架构/design-pattern"
weight = 1

[[languages.zh.menu.main]]
parent = "模式架构"
name = "微服务架构"
url = "模式架构/micro-service"
weight = 2

##
[[languages.zh.menu.main]]
identifier = "面试"
name = "面试"
url = "面试问答"
weight = 8

##
[[languages.zh.menu.main]]
identifier = "管理"
name = "管理"
url = "管理路径"
weight = 9

##
[[languages.zh.menu.main]]
name = "开源"
url = "开源项目"
weight = 10